# Generated by Django 3.0.6 on 2020-05-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deductions',
            fields=[
                ('deductID', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('deductDesc', models.CharField(max_length=50)),
                ('deduct', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empID', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Employee ID')),
                ('lastName', models.CharField(max_length=50, verbose_name='Last Name')),
                ('firstName', models.CharField(max_length=50, verbose_name='First Name')),
                ('middleName', models.CharField(blank=True, max_length=50, verbose_name='Middle Name')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('contactNo', models.CharField(max_length=12, verbose_name='Contact Number')),
                ('job', models.CharField(max_length=30, verbose_name='Job')),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('jobID', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('jobDesc', models.CharField(max_length=50)),
                ('salary', models.FloatField()),
            ],
        ),
    ]
